// Independent curriculum expectations: stage links stay within the selected course track.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {launch}=require('./browser');
const base=process.env.QA_BASE_URL||'http://127.0.0.1:8793',shots=process.env.QA_SHOTS||'/tmp/sand-to-gpu-reader-cleanup';
const targets={survey:['#/s/02','#/s/03','#/s/06','#/s/09','#/s/10'],deep:['#/m/01','#/m/05','#/m/11','#/m/16','#/m/19']};
const phases={survey:[null,0,1,1,1,2,2,2,3,4],deep:[null,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2,3,3,3,4,null,null]};
const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 fs.mkdirSync(shots,{recursive:true});const browser=await launch(),results=[],errors=[];let page;
 async function fresh(route,width=1280,theme='light'){
  page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));await page.setViewport({width,height:900,isMobile:width<500,hasTouch:width<500});await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);
  await page.evaluateOnNewDocument(theme=>{localStorage.setItem('s2g:theme',JSON.stringify(theme));localStorage.setItem('s2g:read',JSON.stringify({1:true}));localStorage.setItem('s2g:quiz',JSON.stringify({1:{score:8,total:8}}));localStorage.setItem('s2g:sread',JSON.stringify({2:true,3:true}));},theme);
  await page.goto(base+'/'+route,{waitUntil:'networkidle0'});await loaded(route);return page;
 }
 async function loaded(route){await page.waitForFunction(route=>{if(location.hash!==route)return false;const m=route.match(/^#\/(s|m)\/(\d+)/);if(!m)return !!document.querySelector('.atlas-journey');const model=(m[1]==='s'?COURSE.survey:COURSE.modules).find(x=>x.n===Number(m[2]));return document.querySelector('#main h1')?.textContent===model.title&&document.querySelectorAll('.stage-ribbon a').length===5;},{timeout:15000},route);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
 async function go(route){await page.evaluate(route=>location.hash=route,route);await loaded(route);}
 async function state(track,phase,route){const current=await page.evaluate(()=>{const links=[...document.querySelectorAll('.stage-ribbon a')];return {hrefs:links.map(a=>a.getAttribute('href')),indices:links.map((a,i)=>a.classList.contains('current')?i:null).filter(x=>x!==null),aria:links.filter(a=>a.getAttribute('aria-current')==='step').length,track:document.querySelector('.track-btn[aria-pressed=true] b')?.textContent,sidebar:document.querySelector('#sidebar a.mod[aria-current=page]')?.getAttribute('href'),progress:document.querySelector('#progress-txt')?.textContent};});assert.deepEqual(current.hrefs,targets[track]);assert.deepEqual(current.indices,phase===null?[]:[phase]);assert.equal(current.aria,phase===null?0:1);assert.equal(current.track,track==='survey'?'Survey':'Deep dive');assert.equal(current.sidebar,route);return current;}
 async function test(name,fn){if(process.env.QA_FILTER&&!new RegExp(process.env.QA_FILTER).test(name))return;try{const detail=await fn();results.push({name,status:'passed',detail:detail||null});console.log('PASS '+name);}catch(error){results.push({name,status:'failed',error:error.stack});console.log('FAIL '+name+': '+error.message);}finally{if(page)await page.close();page=null;}}
 try{
  await test('All32 chapter phase states match their subject, including neutral overviews and references',async()=>{await fresh('#/s/01');let checked=0;for(const track of ['survey','deep'])for(let index=0;index<phases[track].length;index++){const n=track==='survey'?index+1:index,route='#/'+(track==='survey'?'s':'m')+'/'+String(n).padStart(2,'0');await go(route);await state(track,phases[track][index],route);checked++;}return {chapters:checked};});
  for(const width of [1280,375])for(const theme of ['light','dark'])for(const track of ['survey','deep'])await test('Pointer stage destinations '+track+' '+width+' '+theme,async()=>{
   const from=track==='survey'?'#/s/05':'#/m/09';await fresh(from,width,theme);assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),theme);
   await page.$eval('.stage-ribbon',e=>e.scrollIntoView({block:'center',behavior:'instant'}));const rect=await page.$eval('.stage-ribbon',e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,scroll:e.scrollWidth,client:e.clientWidth};});assert(rect.left>=0&&rect.right<=width+1&&rect.scroll<=rect.client+1);await page.screenshot({path:path.join(shots,track+'-'+width+'-'+theme+'.png')});
   const clicks=[];for(let i=0;i<5;i++){await page.click('.stage-ribbon a:nth-child('+(i+1)+')');await loaded(targets[track][i]);const snapshot=await state(track,i,targets[track][i]);assert.equal(parseInt(snapshot.progress),track==='survey'?20:5);const alive=await page.$$eval('.chapter-outline a',links=>links.every(a=>{const parts=a.getAttribute('href').split('/');return document.getElementById(decodeURIComponent(parts.slice(3).join('/')))!==null;}));assert(alive,'Chapter outline must not contain dead anchors');clicks.push({destination:targets[track][i],currentStage:i,progress:snapshot.progress});}
   return {clicks,rect};
  });
  await test('Survey completion updates immediately and remains separate from deep-dive progress',async()=>{
   await fresh('#/s/05');assert.equal(await page.$eval('#progress-txt',e=>parseInt(e.textContent)),20);await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));await page.waitForFunction(()=>JSON.parse(localStorage.getItem('s2g:sread'))[5]===true);await page.waitForFunction(()=>parseInt(document.querySelector('#progress-txt').textContent)===30);assert(await page.$eval('#sidebar a[data-s="5"]',e=>e.classList.contains('read')));await go('#/m/09');assert.equal(await page.$eval('#progress-txt',e=>parseInt(e.textContent)),5);await go('#/s/05');assert.equal(await page.$eval('#progress-txt',e=>parseInt(e.textContent)),30);return {surveyBefore:20,surveyAfter:30,deep:5};
  });
  await test('Removed shell filler stays absent while real figure caveats and navigation remain',async()=>{
   await fresh('#/s/05');const removed=await page.evaluate(()=>({visualLinks:document.querySelectorAll('.visual-jump').length,heroNote:document.querySelector('.chapter-plate')?.textContent.includes('not to scale'),rail:document.querySelector('#rail')?.textContent.includes('Follow your curiosity'),surveyCount:document.querySelector('#sidebar .part-h')?.textContent,caveats:[...document.querySelectorAll('.section-figure')].filter(e=>/not to scale|conceptual schematic|actual coverage depends/i.test(e.textContent)).length,goDeeper:[...document.querySelectorAll('.prose h2')].some(e=>e.textContent==='Go deeper')}));assert.equal(removed.visualLinks,0);assert.equal(removed.heroNote,false);assert.equal(removed.rail,false);assert(!/whole chain in.*chapters/i.test(removed.surveyCount));assert(removed.caveats>0&&removed.goDeeper);await go('#/home');const home=await page.evaluate(()=>({text:document.querySelector('#main').textContent,glossary:!!document.querySelector('a[href="#/m/21"]'),journey:document.querySelectorAll('.atlas-journey a').length}));assert(!/Schematics not to scale|A self-study field guide\. Read, experiment|Explore any stage ↑/.test(home.text));assert(home.glossary&&home.journey===5);for(const width of [1280,375])for(const theme of ['light','dark']){await page.setViewport({width,height:900});await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);await page.$eval('.atlas-footer',e=>e.scrollIntoView({block:'center',behavior:'instant'}));const rect=await page.$eval('.atlas-footer',e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,scroll:e.scrollWidth,client:e.clientWidth};});assert(rect.left>=0&&rect.right<=width+1&&rect.scroll<=rect.client+1);await page.screenshot({path:path.join(shots,'footer-'+width+'-'+theme+'.png')});}return {scientificCaveatsKept:removed.caveats,goDeeperKept:true,homeNavigationKept:true};
  });
 }finally{await browser.close();}
 const root=path.resolve(__dirname,'..'),hash=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'site',file))).digest('hex');
 const report={status:results.every(r=>r.status==='passed')&&!errors.length?'passed':'failed',timestamp:new Date().toISOString(),baseURL:base,expectedStageTargets:targets,expectedPhaseStates:phases,results,pageErrors:errors,sourceHash:hash('content.js'),aiContentHash:hash('ai-content.js'),screenshotsDirectory:shots,limitations:['Real pointer navigation is tested with reduced motion for deterministic coordinates.','Seeded progress belongs to disposable Chromium storage, not user progress.','No narration generation, clipboard action or external AI request is required for these navigation checks.']};
 fs.writeFileSync(process.env.QA_REPORT||path.join(__dirname,'reports/reader-cleanup.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(report.status!=='passed')process.exitCode=1;
})().catch(error=>{console.error(error);process.exitCode=1;});
