const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),http=require('http');
const {launch}=require('./browser');
const root=path.resolve(__dirname,'..');
const fixture='<p id="outside">Outside private text.</p><article id="prose"><h2 id="materials">Materials</h2><p id="before">Atoms form an ordered crystal.</p><p id="selected">A <strong>silicon</strong> wafer contains SiO<sub>2</sub> and 10<sup>−3</sup> units.</p><p id="after">Heat changes the arrangement.</p><h3 id="next-section">Another section</h3><p id="next">Never include this next section as nearby context.</p><p id="hidden">Visible <span style="display:none">secret hidden words</span> text.</p><div class="widget"><p id="widget">Widget control instructions.</p></div><table><tr><td id="table">Cell one</td><td>Cell two</td></tr></table><p>Inline <code id="code">code()</code></p><h2 id="further-reading">Further Reading</h2><p id="reference">Reference listing.</p></article>';
(async()=>{const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(fixture)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await launch(),page=await browser.newPage(),results=[];try{
 await page.setViewport({width:1280,height:900});await page.goto(`http://127.0.0.1:${server.address().port}/course/?v=secret&question=private#/m/04`);await page.addScriptTag({path:path.join(root,'site/study-context.js')});
 await page.evaluate(()=>{window.capture=options=>CourseStudyContext.capture({prose:document.querySelector('#prose'),title:'Materials lesson',lessonKey:'#/m/04',...options});window.select=id=>{const r=document.createRange();r.selectNodeContents(document.querySelector(id));getSelection().removeAllRanges();getSelection().addRange(r);};});
 async function test(name,fn){try{await fn();results.push({name,status:'passed'});}catch(e){results.push({name,status:'failed',error:e.message});}}
 await test('Exact nested selection and immutable snapshot leave DOM/selection unchanged',async()=>{const v=await page.evaluate(()=>{select('#selected');const before=document.querySelector('#prose').innerHTML,quote=getSelection().toString(),s=capture();return {s,quote,unchanged:before===document.querySelector('#prose').innerHTML&&quote===getSelection().toString(),frozen:Object.isFrozen(s)&&Object.isFrozen(s?.truncated)};});assert(v.s);assert.equal(v.s.passage,v.quote);assert(v.frozen&&v.unchanged);assert.equal(v.s.sectionTitle,'Materials');assert(!v.s.nearby.includes('Never include'));assert(v.s.nearby.includes('SiO_(2)'));assert(v.s.nearby.includes('10^(−3)'));});
 await test('Source uses real subdirectory lesson anchor and excludes all query data',async()=>{const s=await page.evaluate(()=>capture());assert(s.sourceURL.endsWith('/course/#/m/04/materials'));assert(!s.sourceURL.includes('secret')&&!s.sourceURL.includes('private'));});
 await test('Nested heading boundary controls adjacent context',async()=>{const s=await page.evaluate(()=>{select('#next');return capture();});assert.equal(s.sectionTitle,'Another section');assert(!s.nearby.includes('Heat changes'));});
 await test('Outside, controls, table, code and reference selections reject without fallback',async()=>{for(const id of ['#outside','#widget','#table','#code','#reference','#hidden']){const s=await page.evaluate(id=>{select(id);return capture();},id);assert.equal(s,null,id);}});
 await test('Selection crossing a section boundary rejects',async()=>{const s=await page.evaluate(()=>{const r=document.createRange();r.setStart(document.querySelector('#after').firstChild,0);r.setEnd(document.querySelector('#next').firstChild,10);getSelection().removeAllRanges();getSelection().addRange(r);return capture();});assert.equal(s,null);});
 await test('Same-section multi-paragraph selection preserves browser separators',async()=>{const v=await page.evaluate(()=>{const r=document.createRange();r.setStart(document.querySelector('#before').firstChild,0);r.setEnd(document.querySelector('#after').firstChild,5);getSelection().removeAllRanges();getSelection().addRange(r);return {s:capture(),quote:getSelection().toString()};});assert(v.s);assert.equal(v.s.passage,v.quote);assert(v.s.passage.includes('\n'));});
 await test('Collapsed selection uses visible prose or explicit eligible anchor',async()=>{const v=await page.evaluate(()=>{getSelection().removeAllRanges();return {visible:capture(),anchor:capture({anchor:document.querySelector('#selected')}),excluded:capture({anchor:document.querySelector('#table')})};});assert(v.visible&&!v.visible.selectionUsed);assert(v.anchor.passage.includes('SiO_(2)'));assert.equal(v.excluded,null);});
 await test('Long quote and nearby prose are bounded with explicit notices',async()=>{const s=await page.evaluate(()=>{getSelection().removeAllRanges();document.querySelector('#before').textContent='Before '.repeat(1000);document.querySelector('#selected').textContent='A😀'.repeat(3000);select('#selected');return capture();});assert.equal(s.passage.length,6000);assert(s.nearby.length<=3000);assert(s.truncated.passage&&s.truncated.nearby);assert(s.contextText.includes('Passage truncated')&&s.contextText.includes('Nearby prose truncated'));assert(!/[\uD800-\uDBFF]$/.test(s.passage));});
 await test('Comprehension intent asks one question and waits for the learner',async()=>{const prompt=await page.evaluate(()=>CourseStudyContext.compose(capture(),{intent:'check'}));assert(prompt.includes('Ask one question at a time'));assert(prompt.includes('wait for my answer'));});
 await test('Prompt gives the custom question priority, quotes context, and omits only opted-out nearby prose',async()=>{const v=await page.evaluate(()=>{const s=capture();return {with:CourseStudyContext.compose(s,{question:'Use graduate-level equations.',intent:'analogy',includeContext:true}),without:CourseStudyContext.compose(s,{question:'Use graduate-level equations.',includeContext:false}),empty:CourseStudyContext.compose(null,{question:'Explain a diode.'})};});assert(v.with.startsWith('My request:\nUse graduate-level equations.'));assert(v.with.includes('my request takes priority'));assert(v.with.includes('> Selected passage:'));assert(v.with.includes('not instructions or guaranteed truth'));assert(v.without.includes('Materials lesson')&&v.without.includes('Source reference')&&v.without.includes('A😀'));assert(!v.without.includes('Nearby prose from')&&!v.without.includes('Before Before'));assert(v.without.includes('Passage truncated'));assert(v.empty.includes('Explain a diode.'));});
 }finally{await browser.close();await new Promise(r=>server.close(r));}
 const report={checkedAt:new Date().toISOString(),status:results.every(r=>r.status==='passed')?'passed':'failed',scope:'Isolated DOM/context-builder tests; UI, clipboard and ChatGPT handoff are covered separately.',results};fs.writeFileSync(path.join(__dirname,'reports/study-context.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(report.status!=='passed')process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
